### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by aputland** [meteor/blaze-tutorial#18]
There are a couple of errors which would be confusing for novice users.
1.2 refers to 'Meteor with React' this tutorial is for Blaze not React.
1.4 Line 5 'Template.app.helpers' there is no template named 'app' so this will cause an error it should be 'Template.maincontainer.helpers'

**Comment by StorytellerCZ** [comment]
Merged a fix for the first issue Yesterday, will look into the second one.

**Comment by StorytellerCZ** [comment]
#16 and #17 should fix this.
